### ISSUE TITLE
dual multiplus parallel vs split phase switch

### ISSUE THREAD

**Issue by DumpySquare** [kwindrem/GuiMods2#1]
I would like to start this thread to discuss and explore options for handling incoming phase changes in a dual multiplus US system.  This seems like one of the more likely places to actually get this to happen.

Scenario 1:  US 50a hookup with two 110v 50a legs, each 180 degrees out of phase
Scenario 2:  Generator that puts out single phase over both legs (or when connecting 30a shore to 50a RV, the plug bridges the legs

The following comment indicates there is a way to fetch the grid config of each multiplus in a GX group, modify and deploy changes.  To me, these mods could be the perfect place to explore options outside of waiting for Victron to release them.

https://community.victronenergy.com/questions/122/multiplus-inverters-setup-in-split-phase-to-match.html?childToView=12027#comment-12027

Other supporting conversations:
https://community.victronenergy.com/questions/98855/split-phase-dual-multiplus-with-generator.html
https://community.victronenergy.com/questions/89089/split-phase-system-configuration-advice.html
https://community.victronenergy.com/questions/7374/onan-gen-split-phase-power-with-2-multiplus-invert.html

I'd also like to help develop/test some of the things your working on.  I'd like to know more about how I can help.

Ben
bunookana at gmail

**Comment by DumpySquare** [comment]
Any thoughts?  Do you know how to get these config parameters through venus os, or are you mainly focused on the UI and data that's already there?

**Comment by kwindrem** [comment]
Matthijs Vader mentions a mechanism to retrieve and restore the complete multi configuration. He didn't explain the mechanism so more details are needed.

Wiring two Multis in parallel requires careful attention to cable lengths in order for the two units to power share prolerly. The typical 30 to 50 amp doggone probably introduces too many variables, but using one leg and ignoring the other might be possible assuming you' be OK with 30 amps total. Switching between parallel and split-phase operation would require changing Multi configuration at the same time to avoid issues (shorting two legs that are out of phase). So there would probably need a lockout that allows changes only with shore power turned off.

I brought up this very issue at the Victron Training tour yesterday in Richmond, CA. Victron's "solution" seems to be to power one Multi and let it power the other through the DC path to the batteries. You'd turn off "switch as a group" off in VEConfig. The result would be two legs of 120 volts 180 degrees apart.

Really this is a huge project far outside of GuiMods/GuiMods2 scope. I'd take this to the Victron community forum. It'll get more attention there.

**Comment by DumpySquare** [comment]
ok.  I was hoping you knew what that mechanism was.  I've been digging through the venus os repo learning about the different services and how everything works.  I will bring this up in the community forum after I've done more digging.  I may come back to this project to get it as a screen on the UI utils you've been working on.  

I've been playing with the different settings related to having a parallel vs split phase system.  Right now, I have a good amount of lithium batteries and solar so, fast charging is not that big of a deal as long as I have some sort of trickle charge from shore.  I've been running on a 10a nema connection for weeks now.   So, typically I run split phase, but I can see scenarios where I would need the generator to quickly charge the batteries.  If i could quickly change to parallel, then I could pull another 15a.  from the genny.  Wow, just explaining it this way kinda makes me wonder if it's worth the work.  

I'll close for now.  Thanks.

Anyway, great work on all the venus os add on stuff!  it's really inspiring!
